baseURL = '.'
languageCode = 'es-es'
title = 'LinkBox'
enableRobotsTXT = true

[menu]
	[[menu.main]]
    pre = "<i class='fa-brands fa-github'></i>"
	name = 'github'
	url = 'https://github.com/deltronik/linkbox'
	post = ""
    weight = 1
	[[menu.main]]
	pre = ""
	name = 'licence'
	url = "https://github.com/deltronik/linkbox/LICENSE"
	post = "<i class='fa-solid fa-file-circle-check'></i>"
	weight = 2

[params]
	google_fonts = [["Josefin+Sans","300"]]
	local_fonts = [{name="Orbit", file="Orbit/Orbit-Regular.ttf"}]
    [params.header]
#	gravatar = "deltronik98@gmail.com"
   	 user = "LinkBox"
	paragraph = "Cuando los electrones se mueven las cosas suceden"
	avatar = "img/avatar/avatar.png"
        [params.header.icons]
        github = "esooo"
		gitlab = "esoo"
		x = "x"
    [params.footer]
    description = "Cuando los electrones se mueven las cosas suceden"
    creator = true
#	license ="esto es una licencia"
[params.style]
	backImg = 'img/background/background.jpg'
	backColor = "white"
		[params.style.user]
		imgSize = "150px"
		imgRad  = "15px"
		imgSeparate = "4em"
		titleSeparate  = "10px"
		titleSize = "2em"
		titleFamily = "system-ui"
		titleColor = "black"
		textColor = "black"
		textSeparate = "15px"
		textSize = "1.1em"
		[params.style.icons]
		color = "black"
		size = "1.5em"
		[params.style.menu]
		textColor = "white"
		textSize = "2em"
		textFamily = "Josefin Sans"
		itemColor = "black"
		itemSeparate = "2em"
		itemSize = "3em"
		itemWidth = "90%"
		itemRad = "15px"
		[params.style.footer]
		backColor = "black"
		footerSize = "auto"
		textSize = "14px"
		textColor = "white"
		footerWidth = "100%"
		rad = "0px"
