[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.115.4"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://link-box.netlify.app"
