name = 'linkbox'
licence = 'MIT'
licenselink = 'https://github.com/deltronik/linkbox/LICENSE'
description = 'LinkBox is a basic and simple theme that allows you to create a landing page that houses multiple links, inspired by LinkTree. '

homepage = 'https://github.com/deltronik/linkbox'
demosite = 'https://github.com/deltronik/linkbox'

tag = ['landig page','linktree alternative','simple theme','company','web development']
feature = ['some','awesome','features','web design','landing page', 'theme development', 'dark','light','minimal','online presence']

[author]
  name = 'deltronik'
  homepage = 'https://www.deltronik.net'
